-- Recintos del organizador con ubicación exacta (Maps).
-- Los partidos guardan una copia denormalizada para que el jugador abra el mapa correcto.

CREATE TABLE IF NOT EXISTS public.recintos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organizador_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  nombre text NOT NULL,
  direccion text,
  maps_url text NOT NULL,
  lat double precision,
  lng double precision,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_recintos_organizador
  ON public.recintos(organizador_id);

CREATE INDEX IF NOT EXISTS idx_recintos_nombre
  ON public.recintos(organizador_id, lower(nombre));

ALTER TABLE public.partidos
  ADD COLUMN IF NOT EXISTS recinto_id bigint REFERENCES public.recintos(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS recinto_maps_url text,
  ADD COLUMN IF NOT EXISTS recinto_lat double precision,
  ADD COLUMN IF NOT EXISTS recinto_lng double precision;

CREATE INDEX IF NOT EXISTS idx_partidos_recinto_id ON public.partidos(recinto_id);

ALTER TABLE public.recintos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Organizador gestiona sus recintos" ON public.recintos;
CREATE POLICY "Organizador gestiona sus recintos"
  ON public.recintos
  FOR ALL
  USING (organizador_id = auth.uid() AND public.is_organizer())
  WITH CHECK (organizador_id = auth.uid() AND public.is_organizer());

DROP POLICY IF EXISTS "Jugadores leen recintos de sus partidos" ON public.recintos;
CREATE POLICY "Jugadores leen recintos de sus partidos"
  ON public.recintos
  FOR SELECT
  USING (
    organizador_id = auth.uid()
    OR EXISTS (
      SELECT 1 FROM public.partidos p
      WHERE p.recinto_id = recintos.id
        AND (
          p.organizador_id = auth.uid()
          OR EXISTS (
            SELECT 1 FROM public.convocatoria_jugadores cj
            WHERE cj.partido_id = p.id AND cj.jugador_id = auth.uid()
          )
          OR EXISTS (
            SELECT 1 FROM public.detalles_partido dp
            WHERE dp.partido_id = p.id AND dp.jugador_id = auth.uid()
          )
        )
    )
  );

COMMENT ON TABLE public.recintos IS 'Lugares guardados por el organizador con link/coords de Maps';
COMMENT ON COLUMN public.partidos.recinto_maps_url IS 'Copia del link exacto al crear/editar el partido';
